### ISSUE TITLE
Is possible add Chromium,Docker,KVM?

### ISSUE THREAD

**Issue by royvu** [michaelforney/oasis#5]
Is possible add Chromium,Docker,KVM?

**Comment by michaelforney** [comment]
chromium: Probably not. Its wayland support is still has a long way to go, and it has *loads* of dependencies.
docker: Do you mean building an oasis docker image, or running docker containers from within oasis? The first is probably pretty easy. Not sure about the second.
kvm: Can you clarify? You can build support for kvm into your kernel as you would normally do.
